name: Publish to Nuget

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        
      - name: Get the Release version tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        
      - name: Update const string BepinEx version field
        run: sed -i 's/"0.0.1"/"${{steps.vars.outputs.tag}}"/g' ExtendedCompiler/build/ExtendedCompiler.targets
        
      - name: Build and Create the package
        run:
          dotnet pack -c Release ExtendedCompiler/ExtendedCompiler.csproj
          -p:Version=${{steps.vars.outputs.tag}}
          -o .
        
      - name: Publish the package to Nuget
        run: dotnet nuget push "*.nupkg" -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
