name: Publish to Nuget

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        
      - name: Get the Release version tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        
      - name: Update targets search path version string
        run: sed -i 's/0.0.1/${{steps.vars.outputs.tag}}/g' ExtendedCompiler/build/ExtendedCompiler.targets
          
      - name: Pack
        run:
          dotnet pack -c Release ExtendedCompiler/ExtendedCompiler.csproj
          -p:Version=${{steps.vars.outputs.tag}}
          -o .
          
      - name: Put the content folder in nupkg
        run: |
          cd ExtendedCompiler
          zip -r ../*.nupkg content/
        
      - name: Publish the package to Nuget
        run: dotnet nuget push "*.nupkg" -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
