name: Publish to Nuget

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: nuget/setup-nuget@v1
      
      - name : Nuget restore
        run: nuget restore ExtendedCompiler.sln
        
      - name: Get the Release version tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        
      - name: Update targets search path version string
        run: sed -i 's/0.0.1/${{steps.vars.outputs.tag}}/g' ExtendedCompiler/build/ExtendedCompiler.targets
          
      - name: Pack
        run:
          msbuild -p:Configuration=Release ExtendedCompiler/ExtendedCompiler.csproj
          -p:Version=${{steps.vars.outputs.tag}}
          /p:OutputPath=.
          
      - name: Build
        run:
          msbuild -t:pack /p:Configuration=Release ExtendedCompiler/ExtendedCompiler.csproj
          -p:Version=${{steps.vars.outputs.tag}}
          /p:OutputPath=./content/
          
      - name: Put the content folder in nupkg
        run: zip -r *.nupkg ./content/
        
      - name: Publish the package to Nuget
        run: dotnet nuget push "*.nupkg" -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
